export const TASK_NEW_TASK = "TASK_NEW_TASK";
export const TASK_UPDATE_TASK = "TASK_UPDATE_TASK";
export const TASK_DELETE_TASK = "TASK_DELETE_TASK";
export const TASK_LOADING_FROM_CLOUD = "TASK_LOADING_FROM_CLOUD";


export const PROJECT_NEW_PROJECT = "PROJECT_NEW_PROJECT";
export const PROJECT_DELETE_PROJECT = "PROJECT_DELETE_PROJECT";
export const PROJECT_LOADING_FROM_CLOUD = "PROJECT_LOADING_FROM_CLOUD";


export const APP_UPDATE_PROJECT_UUID = "APP_UPDATE_PROJECT_UUID";

export const USER_SAVE_USER = "USER_SAVE_USER";
export const USER_LOGOUT_USER = "USER_LOGOUT_USER";
export const USER_SAVE_DATA = "USER_SAVE_DATA";
