export const TASK_NEW_TASK = "TASK_NEW_TASK";
export const TASK_UPDATE_TASK = "TASK_UPDATE_TASK";

export const PROJECT_NEW_PROJECT = "PROJECT_NEW_PROJECT";

export const APP_UPDATE_PROJECT_UUID = "APP_UPDATE_PROJECT_UUID";
